### ISSUE TITLE
Add 404 page or redirects to home page on 404 error instead of blank/empty page

### ISSUE THREAD

**Issue by DestinyJunior** [kromate/vue3-gsap-animations#1]
Hello,

Nice stuff you've got here

so was thinking, can there be redirect for 404 error instead a blank page

i could make a pull request

Thanks

**Comment by kromate** [comment]
Sure sure

**Comment by DestinyJunior** [comment]
Alright thanks, Pull request opened

**Comment by DestinyJunior** [comment]
we can close this now

**Comment by kromate** [comment]
Closed, Thanks for the Fix😃
