### ISSUE TITLE
this is great!

### ISSUE THREAD

**Issue by vesper8** [kromate/vue3-gsap-animations#3]
Thanks so much for taking the time to redo all your work in Vue3 and put it on Github! Super useful as an introduction into gsap and a few other animation libraries.

Would love to see `pageFifteen` and beyond someday! ;-)

**Comment by vesper8** [comment]
P.S. https://vue3-animations.netlify.app/animations/pageFourteen doesn't do anything for me when I hover, all the other pages worked : )

**Comment by kromate** [comment]
Hi, I just opened animation 14 and it works fine.
 probably just reload the page
